[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18.18.0"  # Versão LTS mais recente

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

# Configurações do Netlify para Single Page Applications (SPA)

# Configuração de redirecionamento para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuração de headers para segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"